MyVocal.Web/Controllers/LibraryController.cs
using AutoMapper;
using MyVocal.Data.Infrastructure;
using MyVocal.Model.Models;
using MyVocal.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using static MyVocal.Service.SubjectGroupService;

namespace MyVocal.Web.Controllers
{
    public class LibraryController : Controller
    {
        ISubjectGroupService _subjectGroupService;

        public LibraryController(ISubjectGroupService subjectGroupService)
        {
            this._subjectGroupService = subjectGroupService;
        }
        // GET: Library
        public ActionResult Index()
        {
            ViewBag.pathServer = WebConfigurationManager.AppSettings["location"];
            var listSubjectGroup=_subjectGroupService.GetAll();
            var listSubjectGroupViewModel = Mapper.Map<IEnumerable<SubjectGroup>, IEnumerable<SubjectGroupViewModel>>(listSubjectGroup);
            
            return View(listSubjectGroupViewModel);
        }

        public ActionResult Detail()
        {
            return View();
        }
    }
}

MyVocal.Web/Controllers/TopicController.cs
using AutoMapper;
using MyVocal.Data;
using MyVocal.Model.Models;
using MyVocal.Service;
using MyVocal.Web.Models;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace MyVocal.Web.Controllers
{
    public class TopicController : Controller
    {
        private ISubjectService _subjectService;
        private IWordService _wordService;
        private IApplicationUserSubjectService _applicationUserSubjectService;
      
        //Contructor
        public TopicController(ISubjectService subjectService, IWordService wordService,IApplicationUserSubjectService applicationUserSubjectService)
        {
            this._subjectService = subjectService;
            this._wordService = wordService;
            this._applicationUserSubjectService = applicationUserSubjectService;
        }
        
        //Return all Subject in a subjectGroup as json
        public JsonResult LoadAllTopic(int groupId, int pageIndex = 1, int pageSize = 8)
        {
            //Get subjec from database
            int totalRow = 0;
            IEnumerable<Subject> listTopic = null;
            try
            {
                listTopic = _subjectService.GetByGroupId(groupId, pageIndex, pageSize, out totalRow);
            }
            catch (Exception ex)
            {
                string ex2 = ex.ToString();
            }

            var listSubjectViewModel = Mapper.Map<IEnumerable<Subject>, IEnumerable<SubjectViewModel>>(listTopic);
            //Check is learn 
            foreach(var item in listSubjectViewModel)
            {
                item.isLearn = _applicationUserSubjectService.isLearn(User.Identity.GetUserId(), item.SubjectId);
            }


            return Json(new
            {
                data = listSubjectViewModel,
                total = totalRow,
                status = true
            }, JsonRequestBehavior.AllowGet);
        }

        // GET: Topic
        public ActionResult Index(int groupId)
        {
            ViewBag.GroupId = groupId;
            return View();
        }

        //Learn and practise word in a subject
        public ActionResult LearnTopic(int id)
        {
            //Check user
            if (!string.IsNullOrEmpty(User.Identity.GetUserId()))
            {
                if (!_applicationUserSubjectService.isLearn(User.Identity.GetUserId(), id))
                {
                    ApplicationUser_Subject newRecord = new ApplicationUser_Subject();
                    newRecord.ApplicationUserId = User.Identity.GetUserId();
                    newRecord.SubjectId = id;
                    newRecord.LearnDate = DateTime.Now;

                    _applicationUserSubjectService.Add(newRecord);
                    _applicationUserSubjectService.Save();
                }
            }
            
            ViewBag.Id = id;
            return View();
        }

        //Get all word in a subject and return result is json array
        public JsonResult ListAllBySubjectId(int SubjectId)
        {
            bool status = false;
            IEnumerable<Word> listWord = null;
            try
            {
                listWord = _wordService.GetAllBySubjectId(SubjectId);
                status = true;
            }
            catch (Exception ex)
            {
                string ex2 = ex.ToString();
                status = false;
            }

            //var listWordViewModel = Mapper.Map<IEnumerable<Word>, IEnumerable<WordViewModel>>(listWord);
            return Json(new
            {
                data = listWord,
                status = true
            }, JsonRequestBehavior.AllowGet);
        }

        //Test word in a Subject(Topic)
        public ActionResult TestTopic(int id)
        {
            ViewBag.Id = id;
            return View();
        }

        public ActionResult ResultTestTopic()
        {
            return View();
        }
        
    }
}

MyVocal.Web/Views/Library/Index.cshtml
@model IEnumerable<MyVocal.Web.Models.SubjectGroupViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/shared/_Layout.cshtml";
}

@{
    ViewBag.Title = "Thư viện hệ thống";
    Layout = "~/Views/shared/_Layout.cshtml";
}

@section Styles {
    <link href="@Url.Content("~/Assets/client/css/library/list_library.css")" rel="stylesheet" type="text/css" />
}

@section Scripts
{
    <script src="@Url.Content("~/Assets/client/js/library.js")"></script>
}


<!-- Content Header (Page header) -->
<section class="content-header">
    <h3 style="font-family:OpenSansSemiBold; margin-top:0px">
        Thư viện hệ thống
    </h3>
    <ol class="breadcrumb">
        <li><a href="/he-thong/trang-chu"><i class="fa fa-home" style="font-size:30px;color: #565c5f;"></i>Trang chủ</a></li>
        <li class="active">Danh sách chủ đề</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <div class="row" style="background-color:#4800ff; width:97% ; height:2px; margin-left:15px"></div>
    <div class="row">
        <div class="col-md-12">
        @foreach (var item in Model)
        {
            <div class="col-md-3">
                <div class="view">
                    <div class="caption">
                        <h4>@item.SubjecGroupName</h4>
                        <a href="" rel="tooltip" title="Thêm vào thư viện cá nhân"><span class="glyphicon glyphicon-plus" style="font-size:18px"></span></a>
                        <a href="@Url.Action("Index", "Topic",new {groupId=item.SubjectGroupId})" rel="tooltip" title="Xem chi tiết"><span class="glyphicon glyphicon-eye-open" style="font-size:18px"></span></a>
                    </div>
                    @{ var pathImage = ViewBag.pathServer + item.Image;}
                    <img src=@pathImage  class="img-responsive"/>
                </div>
                <div class="info" style="height:200px">
                    <p style="text-align:justify; color:#4e1818">
                        @item.Description
                    </p>

                </div>
                <div class="stats wb-red-bg">
                    <span class="glyphicon glyphicon-gift" rel="tooltip" title="Số lượng từ mới"> <strong>100</strong></span>
                    <div>
                        <span> <strong>Từ vựng mới</strong></span>
                    </div>

                </div>
            </div>
        }
        </div>

    </div>
</section><!-- /.content -->